### ISSUE TITLE
Охуеть как похуй

### ISSUE THREAD

**Issue by SavokBS** [TheAcelot/srokes-srawl-LEAK#1]
1. То что я дорабатывал в последний раз там есть онлайн бои с структурой
2. Это локалка недоделанная, после нее я создал новую папку где переделывал Вокес
3. Я и так сказал что это хуйня и сам же ее слил
4. Там ничего такого нет, просто бсдс с пакетиками. А ещё некоторые обесценились, так что тебе хуже.
5. Появится кучу говна в сц которое ты сам судить и обсирать будешь.
6. Я освожден от Вокеса в41 и именно тебе будут писать дудки с просьбой помочь
7. Абсолютно все сломано в сливе 

Можешь поплакать ребёночек пока твоя мама под бомбу не попала 😭😨😨😨

**Comment by SavokBS** [comment]
Ты видимо сам сделать не можешь некоторое, вот и залил чтобы не забыть пхпхп

**Comment by TheAcelot** [comment]
ты понимаешь что я слил это только на зло тебе?) я ждал пока твой пердак найдет время встать с хуя хеона и написать этот высер

**Comment by vanyadev228** [comment]
а оцекок лох ващет

**Comment by TheAcelot** [comment]
любовника срани обидели, как печально

**Comment by vanyadev228** [comment]
любовник это когда дикдев сосет ацекоку

**Comment by TheAcelot** [comment]
у тебя бомбит как и совка, да?

**Comment by SavokBS** [comment]
бомбит у твоей мамаши свиньи которая убитая в центре киева валяется

**Comment by TheAcelot** [comment]
ещё сильнее забомбило, значит тебе не все равно на леак и ты плачешь из-за этого
