### ISSUE TITLE
савок лошара

### ISSUE THREAD

**Issue by BreadBSS** [TheAcelot/srokes-srawl-LEAK#2]

**Comment by SavokBS** [comment]
ЗПЗАПЗАЗАПЗАПЗАПЗАПЗАПЗАПЗАПЗ БОЖЕ ТАМ НИЧЕГО НЕТ ДАЖЕ ПАПАЗПЗ

**Comment by TheAcelot** [comment]
согл

**Comment by TheAcelot** [comment]
> ЗПЗАПЗАЗАПЗАПЗАПЗАПЗАПЗАПЗАПЗ БОЖЕ ТАМ НИЧЕГО НЕТ ДАЖЕ ПАПАЗПЗ

Бро, там все запускается + заходит на сервак
